application: markjen-gcptest-scaling
version: 1
runtime: go
api_version: go1

module: auto-worker
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # default value
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 1

handlers:
- url: /.*
  script: _go_app
